const fs = require('fs');
const path = require('path');

// 1. Resolve values from environment variables
const firebaseConfig = {
  apiKey: process.env.FIREBASE_API_KEY || "",
  authDomain: process.env.FIREBASE_AUTH_DOMAIN || "",
  projectId: process.env.FIREBASE_PROJECT_ID || "",
  storageBucket: process.env.FIREBASE_STORAGE_BUCKET || "",
  messagingSenderId: process.env.FIREBASE_MESSAGING_SENDER_ID || "",
  appId: process.env.FIREBASE_APP_ID || "",
  measurementId: process.env.FIREBASE_MEASUREMENT_ID || ""
};

// Check if a single string config was provided
if (process.env.FIREBASE_CONFIG) {
  try {
    const parsed = JSON.parse(process.env.FIREBASE_CONFIG);
    Object.assign(firebaseConfig, parsed);
  } catch (e) {
    console.error("Error parsing FIREBASE_CONFIG JSON string:", e);
  }
}

const openRouterApiKey = process.env.OPENROUTER_API_KEY || "";

// 2. Generate script content
const fileContent = `/**
 * Firebase Config (Auto-generated by generate-config.js during build)
 * Living Archive
 */

window.firebaseConfig = ${JSON.stringify(firebaseConfig, null, 2)};

window.openRouterApiKey = "${openRouterApiKey}";
`;

// 3. Write to script/firebase-config.js
const targetPath = path.join(__dirname, 'script', 'firebase-config.js');

// Ensure directory exists
const dir = path.dirname(targetPath);
if (!fs.existsSync(dir)){
    fs.mkdirSync(dir, { recursive: true });
}

fs.writeFileSync(targetPath, fileContent, 'utf8');
console.log("firebase-config.js successfully generated in script/ directory.");
