@echo off
echo Initializing git...
git init
echo Adding files...
git add .
echo Committing...
git commit -m "Auto-commit from AI agent"
echo Renaming branch...
git branch -M main
echo Setting up remote...
git remote remove origin
git remote add origin https://github.com/sayanjc3639q/Archive.git
echo Pushing...
git push -u origin main
echo Done.
pause
